<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetAffiliate extends BaseJobeetAffiliate
{
  public function __toString()
  {
    return $this->getUrl();
  }
}