<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategory extends BaseJobeetCategory
{

  public function getActiveJobs($max = 10)
  {
    $q = Doctrine_Query::create()
      ->from('JobeetJob j')
      ->where('j.category_id = ?', $this->getId())
      ->limit($max);
   
    return Doctrine_Core::getTable('JobeetJob')->getActiveJobs($q);
  }

}
