job:
  class:   sfDoctrineRouteCollection
  options: { model: JobeetJob }
 
job_show_user:
  url:     /job/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: JobeetJob
    type:  object
    method_for_query: retrieveActiveJob
  param:   { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [GET]
 
# default rules
homepage:
  url:   /
  param: { module: job, action: index }
 
#default_index:
#  url:   /:module
3  param: { action: index }
 
#default:
#  url:   /:module/:action/*
